# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.02
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class Identity(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'auth_challenge_redirect': 'IdentityAuthChallengeRedirect',
        'oidc': 'Oidc',
        'oauth': 'list[Oauth]',
        'eai': 'Eai',
        'ci_oidc': 'CiOidc'
    }

    attribute_map = {
        'auth_challenge_redirect': 'auth_challenge_redirect',
        'oidc': 'oidc',
        'oauth': 'oauth',
        'eai': 'eai',
        'ci_oidc': 'ci_oidc'
    }

    def __init__(self, auth_challenge_redirect=None, oidc=None, oauth=None, eai=None, ci_oidc=None):  # noqa: E501
        """Identity - a model defined in OpenAPI"""  # noqa: E501

        self._auth_challenge_redirect = None
        self._oidc = None
        self._oauth = None
        self._eai = None
        self._ci_oidc = None
        self.discriminator = None

        if auth_challenge_redirect is not None:
            self.auth_challenge_redirect = auth_challenge_redirect
        if oidc is not None:
            self.oidc = oidc
        if oauth is not None:
            self.oauth = oauth
        if eai is not None:
            self.eai = eai
        if ci_oidc is not None:
            self.ci_oidc = ci_oidc

    @property
    def auth_challenge_redirect(self):
        """Gets the auth_challenge_redirect of this Identity.  # noqa: E501


        :return: The auth_challenge_redirect of this Identity.  # noqa: E501
        :rtype: IdentityAuthChallengeRedirect
        """
        return self._auth_challenge_redirect

    @auth_challenge_redirect.setter
    def auth_challenge_redirect(self, auth_challenge_redirect):
        """Sets the auth_challenge_redirect of this Identity.


        :param auth_challenge_redirect: The auth_challenge_redirect of this Identity.  # noqa: E501
        :type: IdentityAuthChallengeRedirect
        """

        self._auth_challenge_redirect = auth_challenge_redirect

    @property
    def oidc(self):
        """Gets the oidc of this Identity.  # noqa: E501


        :return: The oidc of this Identity.  # noqa: E501
        :rtype: Oidc
        """
        return self._oidc

    @oidc.setter
    def oidc(self, oidc):
        """Sets the oidc of this Identity.


        :param oidc: The oidc of this Identity.  # noqa: E501
        :type: Oidc
        """

        self._oidc = oidc

    @property
    def oauth(self):
        """Gets the oauth of this Identity.  # noqa: E501

        This node is used to specify OAuth introspection endpoints which can be used by the reverse proxy to authenticate OAuth bearer tokens.  # noqa: E501

        :return: The oauth of this Identity.  # noqa: E501
        :rtype: list[Oauth]
        """
        return self._oauth

    @oauth.setter
    def oauth(self, oauth):
        """Sets the oauth of this Identity.

        This node is used to specify OAuth introspection endpoints which can be used by the reverse proxy to authenticate OAuth bearer tokens.  # noqa: E501

        :param oauth: The oauth of this Identity.  # noqa: E501
        :type: list[Oauth]
        """

        self._oauth = oauth

    @property
    def eai(self):
        """Gets the eai of this Identity.  # noqa: E501


        :return: The eai of this Identity.  # noqa: E501
        :rtype: Eai
        """
        return self._eai

    @eai.setter
    def eai(self, eai):
        """Sets the eai of this Identity.


        :param eai: The eai of this Identity.  # noqa: E501
        :type: Eai
        """

        self._eai = eai

    @property
    def ci_oidc(self):
        """Gets the ci_oidc of this Identity.  # noqa: E501


        :return: The ci_oidc of this Identity.  # noqa: E501
        :rtype: CiOidc
        """
        return self._ci_oidc

    @ci_oidc.setter
    def ci_oidc(self, ci_oidc):
        """Sets the ci_oidc of this Identity.


        :param ci_oidc: The ci_oidc of this Identity.  # noqa: E501
        :type: CiOidc
        """

        self._ci_oidc = ci_oidc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Identity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Identity):
            return True

        return self.to_dict() != other.to_dict()
