# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 26.06
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class PoliciesHttpTransformationsUtilities(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'rule': 'str'
    }

    attribute_map = {
        'name': 'name',
        'rule': 'rule'
    }

    def __init__(self, name=None, rule=None):  # noqa: E501
        """PoliciesHttpTransformationsUtilities - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._rule = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if rule is not None:
            self.rule = rule

    @property
    def name(self):
        """Gets the name of this PoliciesHttpTransformationsUtilities.  # noqa: E501

        Name of the utility script. This is the name which can be used when requiring the script in transformation rules.   # noqa: E501

        :return: The name of this PoliciesHttpTransformationsUtilities.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PoliciesHttpTransformationsUtilities.

        Name of the utility script. This is the name which can be used when requiring the script in transformation rules.   # noqa: E501

        :param name: The name of this PoliciesHttpTransformationsUtilities.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def rule(self):
        """Gets the rule of this PoliciesHttpTransformationsUtilities.  # noqa: E501

        The Lua script content for this utility.   # noqa: E501

        :return: The rule of this PoliciesHttpTransformationsUtilities.  # noqa: E501
        :rtype: str
        """
        return self._rule

    @rule.setter
    def rule(self, rule):
        """Sets the rule of this PoliciesHttpTransformationsUtilities.

        The Lua script content for this utility.   # noqa: E501

        :param rule: The rule of this PoliciesHttpTransformationsUtilities.  # noqa: E501
        :type: str
        """

        self._rule = rule

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoliciesHttpTransformationsUtilities):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PoliciesHttpTransformationsUtilities):
            return True

        return self.to_dict() != other.to_dict()
