# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 26.09
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class ResourceServerSslCfg(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tlsv10': 'bool',
        'tlsv11': 'bool',
        'tlsv12': 'bool',
        'tlsv13': 'bool',
        'key_agreement': 'str',
        'supported_groups': 'list[str]',
        'fips_processing': 'bool'
    }

    attribute_map = {
        'tlsv10': 'tlsv10',
        'tlsv11': 'tlsv11',
        'tlsv12': 'tlsv12',
        'tlsv13': 'tlsv13',
        'key_agreement': 'key_agreement',
        'supported_groups': 'supported_groups',
        'fips_processing': 'fips_processing'
    }

    def __init__(self, tlsv10=None, tlsv11=None, tlsv12=None, tlsv13=None, key_agreement=None, supported_groups=None, fips_processing=None):  # noqa: E501
        """ResourceServerSslCfg - a model defined in OpenAPI"""  # noqa: E501

        self._tlsv10 = None
        self._tlsv11 = None
        self._tlsv12 = None
        self._tlsv13 = None
        self._key_agreement = None
        self._supported_groups = None
        self._fips_processing = None
        self.discriminator = None

        if tlsv10 is not None:
            self.tlsv10 = tlsv10
        if tlsv11 is not None:
            self.tlsv11 = tlsv11
        if tlsv12 is not None:
            self.tlsv12 = tlsv12
        if tlsv13 is not None:
            self.tlsv13 = tlsv13
        if key_agreement is not None:
            self.key_agreement = key_agreement
        if supported_groups is not None:
            self.supported_groups = supported_groups
        if fips_processing is not None:
            self.fips_processing = fips_processing

    @property
    def tlsv10(self):
        """Gets the tlsv10 of this ResourceServerSslCfg.  # noqa: E501

        A boolean which indicates whether or not TLS v1.0 is enabled.   # noqa: E501

        :return: The tlsv10 of this ResourceServerSslCfg.  # noqa: E501
        :rtype: bool
        """
        return self._tlsv10

    @tlsv10.setter
    def tlsv10(self, tlsv10):
        """Sets the tlsv10 of this ResourceServerSslCfg.

        A boolean which indicates whether or not TLS v1.0 is enabled.   # noqa: E501

        :param tlsv10: The tlsv10 of this ResourceServerSslCfg.  # noqa: E501
        :type: bool
        """

        self._tlsv10 = tlsv10

    @property
    def tlsv11(self):
        """Gets the tlsv11 of this ResourceServerSslCfg.  # noqa: E501

        A boolean which indicates whether or not TLS v1.1 is enabled.   # noqa: E501

        :return: The tlsv11 of this ResourceServerSslCfg.  # noqa: E501
        :rtype: bool
        """
        return self._tlsv11

    @tlsv11.setter
    def tlsv11(self, tlsv11):
        """Sets the tlsv11 of this ResourceServerSslCfg.

        A boolean which indicates whether or not TLS v1.1 is enabled.   # noqa: E501

        :param tlsv11: The tlsv11 of this ResourceServerSslCfg.  # noqa: E501
        :type: bool
        """

        self._tlsv11 = tlsv11

    @property
    def tlsv12(self):
        """Gets the tlsv12 of this ResourceServerSslCfg.  # noqa: E501

        A boolean which indicates whether or not TLS v1.2 is enabled.   # noqa: E501

        :return: The tlsv12 of this ResourceServerSslCfg.  # noqa: E501
        :rtype: bool
        """
        return self._tlsv12

    @tlsv12.setter
    def tlsv12(self, tlsv12):
        """Sets the tlsv12 of this ResourceServerSslCfg.

        A boolean which indicates whether or not TLS v1.2 is enabled.   # noqa: E501

        :param tlsv12: The tlsv12 of this ResourceServerSslCfg.  # noqa: E501
        :type: bool
        """

        self._tlsv12 = tlsv12

    @property
    def tlsv13(self):
        """Gets the tlsv13 of this ResourceServerSslCfg.  # noqa: E501

        A boolean which indicates whether or not TLS v1.3 is enabled.   # noqa: E501

        :return: The tlsv13 of this ResourceServerSslCfg.  # noqa: E501
        :rtype: bool
        """
        return self._tlsv13

    @tlsv13.setter
    def tlsv13(self, tlsv13):
        """Sets the tlsv13 of this ResourceServerSslCfg.

        A boolean which indicates whether or not TLS v1.3 is enabled.   # noqa: E501

        :param tlsv13: The tlsv13 of this ResourceServerSslCfg.  # noqa: E501
        :type: bool
        """

        self._tlsv13 = tlsv13

    @property
    def key_agreement(self):
        """Gets the key_agreement of this ResourceServerSslCfg.  # noqa: E501

        Control the algorithms and parameters used in key agreement for TLSv1.2 and TLSv1.3.  If custom is specified, the `supported_groups` configuration  must specify the named groups to use in the key exchange.  For other entries, the named groups will be determined  automatically.   # noqa: E501

        :return: The key_agreement of this ResourceServerSslCfg.  # noqa: E501
        :rtype: str
        """
        return self._key_agreement

    @key_agreement.setter
    def key_agreement(self, key_agreement):
        """Sets the key_agreement of this ResourceServerSslCfg.

        Control the algorithms and parameters used in key agreement for TLSv1.2 and TLSv1.3.  If custom is specified, the `supported_groups` configuration  must specify the named groups to use in the key exchange.  For other entries, the named groups will be determined  automatically.   # noqa: E501

        :param key_agreement: The key_agreement of this ResourceServerSslCfg.  # noqa: E501
        :type: str
        """
        allowed_values = ["hybrid-pqc-supported", "nonhybrid-pqc-supported", "provider-default", "custom"]  # noqa: E501
        if key_agreement not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `key_agreement` ({0}), must be one of {1}"  # noqa: E501
                .format(key_agreement, allowed_values)
            )

        self._key_agreement = key_agreement

    @property
    def supported_groups(self):
        """Gets the supported_groups of this ResourceServerSslCfg.  # noqa: E501

        Control which named groups to allow in the TLSv1.2 and  TLSv1.3 key agreement. It is only used when `key_agreement` is set to `custom`. ### Supported Groups   - `ECDHE_X25519MLKEM768`   - `ECDHE_X25519`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SECP256R1`   - `ECDHE_SecP384r1MLKEM1024`   - `ECDHE_SECP384R1`   - `ECDHE_SECP521R1`   - `ECDHE_X448`   - `MLKEM768`   - `MLKEM1024` ### Supported Groups for TLSv1.3 The following groups can only be configured when TLSv1.3 is enabled:   - `ECDHE_X25519MLKEM768`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SecP384r1MLKEM1024`   - `MLKEM768`   - `MLKEM1024`   # noqa: E501

        :return: The supported_groups of this ResourceServerSslCfg.  # noqa: E501
        :rtype: list[str]
        """
        return self._supported_groups

    @supported_groups.setter
    def supported_groups(self, supported_groups):
        """Sets the supported_groups of this ResourceServerSslCfg.

        Control which named groups to allow in the TLSv1.2 and  TLSv1.3 key agreement. It is only used when `key_agreement` is set to `custom`. ### Supported Groups   - `ECDHE_X25519MLKEM768`   - `ECDHE_X25519`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SECP256R1`   - `ECDHE_SecP384r1MLKEM1024`   - `ECDHE_SECP384R1`   - `ECDHE_SECP521R1`   - `ECDHE_X448`   - `MLKEM768`   - `MLKEM1024` ### Supported Groups for TLSv1.3 The following groups can only be configured when TLSv1.3 is enabled:   - `ECDHE_X25519MLKEM768`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SecP384r1MLKEM1024`   - `MLKEM768`   - `MLKEM1024`   # noqa: E501

        :param supported_groups: The supported_groups of this ResourceServerSslCfg.  # noqa: E501
        :type: list[str]
        """

        self._supported_groups = supported_groups

    @property
    def fips_processing(self):
        """Gets the fips_processing of this ResourceServerSslCfg.  # noqa: E501

        A boolean which indicates whether FIPS 140 certified cryptography providers should be used for communication with the protected  application.   The FIPS 140 compliance level depends on the version of the  cryptography provider in use. By default, this will be FIPS 140-3.  If version 8 of the cryptography provider is used, due to TLS 1.1  or earlier being enabled, this will be FIPS 140-2.   # noqa: E501

        :return: The fips_processing of this ResourceServerSslCfg.  # noqa: E501
        :rtype: bool
        """
        return self._fips_processing

    @fips_processing.setter
    def fips_processing(self, fips_processing):
        """Sets the fips_processing of this ResourceServerSslCfg.

        A boolean which indicates whether FIPS 140 certified cryptography providers should be used for communication with the protected  application.   The FIPS 140 compliance level depends on the version of the  cryptography provider in use. By default, this will be FIPS 140-3.  If version 8 of the cryptography provider is used, due to TLS 1.1  or earlier being enabled, this will be FIPS 140-2.   # noqa: E501

        :param fips_processing: The fips_processing of this ResourceServerSslCfg.  # noqa: E501
        :type: bool
        """

        self._fips_processing = fips_processing

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceServerSslCfg):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResourceServerSslCfg):
            return True

        return self.to_dict() != other.to_dict()
