# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 26.03
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class ServicesRedisSsl(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'trust_certificates': 'list[str]',
        'client_certificate': 'list[str]',
        'sni': 'str',
        'key_agreement': 'str',
        'supported_groups': 'list[str]'
    }

    attribute_map = {
        'trust_certificates': 'trust_certificates',
        'client_certificate': 'client_certificate',
        'sni': 'sni',
        'key_agreement': 'key_agreement',
        'supported_groups': 'supported_groups'
    }

    def __init__(self, trust_certificates=None, client_certificate=None, sni=None, key_agreement='provider-default', supported_groups=None):  # noqa: E501
        """ServicesRedisSsl - a model defined in OpenAPI"""  # noqa: E501

        self._trust_certificates = None
        self._client_certificate = None
        self._sni = None
        self._key_agreement = None
        self._supported_groups = None
        self.discriminator = None

        if trust_certificates is not None:
            self.trust_certificates = trust_certificates
        if client_certificate is not None:
            self.client_certificate = client_certificate
        if sni is not None:
            self.sni = sni
        if key_agreement is not None:
            self.key_agreement = key_agreement
        if supported_groups is not None:
            self.supported_groups = supported_groups

    @property
    def trust_certificates(self):
        """Gets the trust_certificates of this ServicesRedisSsl.  # noqa: E501

        The PEM based certificates which are to be trusted when communicating with the Redis server.  The trusted certificates should include the CA certificate for the Redis server certificate, as well as any intermediate certificates used to sign the client certificate (if mutual authentication is in use).  SSL/TLS will not be used when communicating with the Redis server if no trust certificates are specified.   # noqa: E501

        :return: The trust_certificates of this ServicesRedisSsl.  # noqa: E501
        :rtype: list[str]
        """
        return self._trust_certificates

    @trust_certificates.setter
    def trust_certificates(self, trust_certificates):
        """Sets the trust_certificates of this ServicesRedisSsl.

        The PEM based certificates which are to be trusted when communicating with the Redis server.  The trusted certificates should include the CA certificate for the Redis server certificate, as well as any intermediate certificates used to sign the client certificate (if mutual authentication is in use).  SSL/TLS will not be used when communicating with the Redis server if no trust certificates are specified.   # noqa: E501

        :param trust_certificates: The trust_certificates of this ServicesRedisSsl.  # noqa: E501
        :type: list[str]
        """

        self._trust_certificates = trust_certificates

    @property
    def client_certificate(self):
        """Gets the client_certificate of this ServicesRedisSsl.  # noqa: E501

        The PEM based personal certificate files which will be used when performing mutual authentication with the resource server.  These certificate files should include the private key, a certificate signed with the private key, and the signer certificate or signer certificate chain (if required).   # noqa: E501

        :return: The client_certificate of this ServicesRedisSsl.  # noqa: E501
        :rtype: list[str]
        """
        return self._client_certificate

    @client_certificate.setter
    def client_certificate(self, client_certificate):
        """Sets the client_certificate of this ServicesRedisSsl.

        The PEM based personal certificate files which will be used when performing mutual authentication with the resource server.  These certificate files should include the private key, a certificate signed with the private key, and the signer certificate or signer certificate chain (if required).   # noqa: E501

        :param client_certificate: The client_certificate of this ServicesRedisSsl.  # noqa: E501
        :type: list[str]
        """

        self._client_certificate = client_certificate

    @property
    def sni(self):
        """Gets the sni of this ServicesRedisSsl.  # noqa: E501

        The Server Name Indication (SNI) value which is provided when establishing the SSL connection with the Redis server.   # noqa: E501

        :return: The sni of this ServicesRedisSsl.  # noqa: E501
        :rtype: str
        """
        return self._sni

    @sni.setter
    def sni(self, sni):
        """Sets the sni of this ServicesRedisSsl.

        The Server Name Indication (SNI) value which is provided when establishing the SSL connection with the Redis server.   # noqa: E501

        :param sni: The sni of this ServicesRedisSsl.  # noqa: E501
        :type: str
        """

        self._sni = sni

    @property
    def key_agreement(self):
        """Gets the key_agreement of this ServicesRedisSsl.  # noqa: E501

        Control the algorithms and parameters used in key agreement for TLSv1.2 and TLSv1.3.  If custom is specified, the `supported_groups` configuration  must specify the named groups to use in the key exchange.  For other entries, the named groups will be determined  automatically.   # noqa: E501

        :return: The key_agreement of this ServicesRedisSsl.  # noqa: E501
        :rtype: str
        """
        return self._key_agreement

    @key_agreement.setter
    def key_agreement(self, key_agreement):
        """Sets the key_agreement of this ServicesRedisSsl.

        Control the algorithms and parameters used in key agreement for TLSv1.2 and TLSv1.3.  If custom is specified, the `supported_groups` configuration  must specify the named groups to use in the key exchange.  For other entries, the named groups will be determined  automatically.   # noqa: E501

        :param key_agreement: The key_agreement of this ServicesRedisSsl.  # noqa: E501
        :type: str
        """
        allowed_values = ["hybrid-pqc-supported", "nonhybrid-pqc-supported", "provider-default", "custom"]  # noqa: E501
        if key_agreement not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `key_agreement` ({0}), must be one of {1}"  # noqa: E501
                .format(key_agreement, allowed_values)
            )

        self._key_agreement = key_agreement

    @property
    def supported_groups(self):
        """Gets the supported_groups of this ServicesRedisSsl.  # noqa: E501

        Control which named groups to allow in the TLSv1.2 and  TLSv1.3 key agreement. It is only used when `key_agreement` is set to `custom`. ### Supported Groups    - `ECDHE_X25519MLKEM768`   - `ECDHE_X25519`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SECP256R1`   - `ECDHE_SecP384r1MLKEM1024`   - `ECDHE_SECP384R1`   - `ECDHE_SECP521R1`   - `ECDHE_X448`   - `MLKEM768`   - `MLKEM1024`  ### Supported Groups for TLSv1.3 The following groups can only be configured when TLSv1.3 is enabled:    - `ECDHE_X25519MLKEM768`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SecP384r1MLKEM1024`   - `MLKEM768`   - `MLKEM1024`   # noqa: E501

        :return: The supported_groups of this ServicesRedisSsl.  # noqa: E501
        :rtype: list[str]
        """
        return self._supported_groups

    @supported_groups.setter
    def supported_groups(self, supported_groups):
        """Sets the supported_groups of this ServicesRedisSsl.

        Control which named groups to allow in the TLSv1.2 and  TLSv1.3 key agreement. It is only used when `key_agreement` is set to `custom`. ### Supported Groups    - `ECDHE_X25519MLKEM768`   - `ECDHE_X25519`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SECP256R1`   - `ECDHE_SecP384r1MLKEM1024`   - `ECDHE_SECP384R1`   - `ECDHE_SECP521R1`   - `ECDHE_X448`   - `MLKEM768`   - `MLKEM1024`  ### Supported Groups for TLSv1.3 The following groups can only be configured when TLSv1.3 is enabled:    - `ECDHE_X25519MLKEM768`   - `ECDHE_SecP256r1MLKEM768`   - `ECDHE_SecP384r1MLKEM1024`   - `MLKEM768`   - `MLKEM1024`   # noqa: E501

        :param supported_groups: The supported_groups of this ServicesRedisSsl.  # noqa: E501
        :type: list[str]
        """

        self._supported_groups = supported_groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServicesRedisSsl):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServicesRedisSsl):
            return True

        return self.to_dict() != other.to_dict()
