# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 26.06
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class ServerClientConnections(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'connect_timeout': 'float',
        'persistent_timeout': 'float',
        'intra_request_timeout': 'float'
    }

    attribute_map = {
        'connect_timeout': 'connect_timeout',
        'persistent_timeout': 'persistent_timeout',
        'intra_request_timeout': 'intra_request_timeout'
    }

    def __init__(self, connect_timeout=120, persistent_timeout=5, intra_request_timeout=60):  # noqa: E501
        """ServerClientConnections - a model defined in OpenAPI"""  # noqa: E501

        self._connect_timeout = None
        self._persistent_timeout = None
        self._intra_request_timeout = None
        self.discriminator = None

        if connect_timeout is not None:
            self.connect_timeout = connect_timeout
        if persistent_timeout is not None:
            self.persistent_timeout = persistent_timeout
        if intra_request_timeout is not None:
            self.intra_request_timeout = intra_request_timeout

    @property
    def connect_timeout(self):
        """Gets the connect_timeout of this ServerClientConnections.  # noqa: E501

        Initial client connection timeout in seconds. This is the maximum time to wait for the initial connection from a client.   # noqa: E501

        :return: The connect_timeout of this ServerClientConnections.  # noqa: E501
        :rtype: float
        """
        return self._connect_timeout

    @connect_timeout.setter
    def connect_timeout(self, connect_timeout):
        """Sets the connect_timeout of this ServerClientConnections.

        Initial client connection timeout in seconds. This is the maximum time to wait for the initial connection from a client.   # noqa: E501

        :param connect_timeout: The connect_timeout of this ServerClientConnections.  # noqa: E501
        :type: float
        """
        if (connect_timeout is not None and connect_timeout < 0):  # noqa: E501
            raise ValueError("Invalid value for `connect_timeout`, must be a value greater than or equal to `0`")  # noqa: E501

        self._connect_timeout = connect_timeout

    @property
    def persistent_timeout(self):
        """Gets the persistent_timeout of this ServerClientConnections.  # noqa: E501

        HTTP/1.1 persistent connection timeout in seconds. This only affects connections to clients, not backend systems.   # noqa: E501

        :return: The persistent_timeout of this ServerClientConnections.  # noqa: E501
        :rtype: float
        """
        return self._persistent_timeout

    @persistent_timeout.setter
    def persistent_timeout(self, persistent_timeout):
        """Sets the persistent_timeout of this ServerClientConnections.

        HTTP/1.1 persistent connection timeout in seconds. This only affects connections to clients, not backend systems.   # noqa: E501

        :param persistent_timeout: The persistent_timeout of this ServerClientConnections.  # noqa: E501
        :type: float
        """
        if (persistent_timeout is not None and persistent_timeout < 0):  # noqa: E501
            raise ValueError("Invalid value for `persistent_timeout`, must be a value greater than or equal to `0`")  # noqa: E501

        self._persistent_timeout = persistent_timeout

    @property
    def intra_request_timeout(self):
        """Gets the intra_request_timeout of this ServerClientConnections.  # noqa: E501

        Intra-request timeout in seconds. This is the timeout between data received or sent for a given request, but not the first read. When this value is non-zero, it also enables timeouts on HTTP writes to clients and causes a TCP RST packet to be sent if a connection timeout occurs on non-first data I/O.   # noqa: E501

        :return: The intra_request_timeout of this ServerClientConnections.  # noqa: E501
        :rtype: float
        """
        return self._intra_request_timeout

    @intra_request_timeout.setter
    def intra_request_timeout(self, intra_request_timeout):
        """Sets the intra_request_timeout of this ServerClientConnections.

        Intra-request timeout in seconds. This is the timeout between data received or sent for a given request, but not the first read. When this value is non-zero, it also enables timeouts on HTTP writes to clients and causes a TCP RST packet to be sent if a connection timeout occurs on non-first data I/O.   # noqa: E501

        :param intra_request_timeout: The intra_request_timeout of this ServerClientConnections.  # noqa: E501
        :type: float
        """
        if (intra_request_timeout is not None and intra_request_timeout < 0):  # noqa: E501
            raise ValueError("Invalid value for `intra_request_timeout`, must be a value greater than or equal to `0`")  # noqa: E501

        self._intra_request_timeout = intra_request_timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerClientConnections):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServerClientConnections):
            return True

        return self.to_dict() != other.to_dict()
