# coding: utf-8

"""
    IBM Application Gateway Configuration Specification (OpenAPI)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 26.06
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

class ServerHttp2Tuning(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'max_connection_duration': 'float'
    }

    attribute_map = {
        'max_connection_duration': 'max_connection_duration'
    }

    def __init__(self, max_connection_duration=120):  # noqa: E501
        """ServerHttp2Tuning - a model defined in OpenAPI"""  # noqa: E501

        self._max_connection_duration = None
        self.discriminator = None

        if max_connection_duration is not None:
            self.max_connection_duration = max_connection_duration

    @property
    def max_connection_duration(self):
        """Gets the max_connection_duration of this ServerHttp2Tuning.  # noqa: E501

        Maximum duration in seconds for an HTTP/2 connection. The connection will be closed if this limit is reached. This setting applies to HTTP/2 connections for all interfaces.   # noqa: E501

        :return: The max_connection_duration of this ServerHttp2Tuning.  # noqa: E501
        :rtype: float
        """
        return self._max_connection_duration

    @max_connection_duration.setter
    def max_connection_duration(self, max_connection_duration):
        """Sets the max_connection_duration of this ServerHttp2Tuning.

        Maximum duration in seconds for an HTTP/2 connection. The connection will be closed if this limit is reached. This setting applies to HTTP/2 connections for all interfaces.   # noqa: E501

        :param max_connection_duration: The max_connection_duration of this ServerHttp2Tuning.  # noqa: E501
        :type: float
        """
        if (max_connection_duration is not None and max_connection_duration < 0):  # noqa: E501
            raise ValueError("Invalid value for `max_connection_duration`, must be a value greater than or equal to `0`")  # noqa: E501

        self._max_connection_duration = max_connection_duration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerHttp2Tuning):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServerHttp2Tuning):
            return True

        return self.to_dict() != other.to_dict()
