kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 

metadata:
  name: aggregate-ibm-app-gateway-crd-edit 
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
    
rules:
- apiGroups: ["security.ibm.com"] 
  resources: ["ibm-application-gateway"] 
  verbs: 
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"
    - "delete"
    - "deletecollection" 
  
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: aggregate-ibm-app-gateway-crd-view 
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
rules:
- apiGroups: ["security.ibm.com"] 
  resources: ["ibm-application-gateway"] 
  verbs:
    - "get"
    - "list"
    - "watch"

